#コンテキスト名
server.servlet.context-path=/practice
#ポート番号
server.port=5555

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xepdb1
spring.datasource.username=spring_practice
spring.datasource.password=systemsss